ARG CR_URL
FROM  $CR_URL/liquibase/liquibase:3.10
ARG BUILD_ID

ENV DATABASE_SERVER ${DATABASE_SERVER:-NOT_DEFINED}
ENV DATABASE_PORT ${DATABASE_PORT:-NOT_DEFINED}
ENV DATABASE_USER ${DATABASE_USER:-NOT_DEFINED}
ENV DATABASE_PASS ${DATABASE_PASS:-NOT_DEFINED}
ENV DATABASE_DB ${DATABASE_PASS:-NOT_DEFINED}
ENV DATABASE_DRIVER ${DATABASE_DRIVER:-NOT_DEFINED}

WORKDIR /liquibase

COPY src/ src/
RUN echo $BUILD_ID > $BUILD_ID.log
